# Generated by Django 3.0.4 on 2020-03-23 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('invoiceid', models.IntegerField(primary_key=True, serialize=False)),
                ('invoicedate', models.DateTimeField()),
                ('billingaddress', models.CharField(max_length=70)),
                ('billingcity', models.CharField(max_length=40)),
                ('billingstate', models.CharField(blank=True, max_length=40, null=True)),
                ('billingcountry', models.CharField(max_length=40)),
                ('billingpostalcode', models.CharField(blank=True, max_length=10, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('customerid', models.ForeignKey(db_column='customerid', on_delete=django.db.models.deletion.DO_NOTHING, to='customers.Customer')),
            ],
            options={
                'db_table': 'invoice',
            },
        ),
    ]
