# Generated by Django 3.0.4 on 2020-06-01 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_auto_20200601_0649'),
        ('invoices', '0002_auto_20200324_0620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='invoiceid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='customerid',
            new_name='customer',
        ),
        migrations.AlterField(
            model_name='invoice',
            name='billingaddress',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='billingcity',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='billingcountry',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoicedate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
