# Generated by Django 3.0.4 on 2020-05-31 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('actionType', models.CharField(max_length=150)),
                ('entity', models.CharField(max_length=100)),
                ('entityid', models.IntegerField(null=True)),
                ('user', models.CharField(max_length=10)),
                ('payload', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'audit',
            },
        ),
    ]
