# Generated by Django 3.0.4 on 2020-05-31 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audit',
            name='user',
            field=models.TextField(max_length=10),
        ),
    ]
