# Generated by Django 3.0.4 on 2020-05-31 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0002_auto_20200531_2333'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audit',
            old_name='user',
            new_name='user_id',
        ),
    ]
