# Generated by Django 3.0.4 on 2020-05-17 02:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0002_audit_entityid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audit',
            old_name='entityId',
            new_name='entityid',
        ),
    ]
