# Generated by Django 3.0.4 on 2020-06-01 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audits', '0003_auto_20200531_2346'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audit',
            old_name='actionType',
            new_name='actiontype',
        ),
    ]
