# Generated by Django 3.0.4 on 2020-06-01 00:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='playlist',
            old_name='playlistid',
            new_name='id',
        ),
    ]
