# Generated by Django 3.0.4 on 2020-03-24 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_auto_20200324_0620'),
        ('mediaTypes', '0001_initial'),
        ('genres', '0001_initial'),
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='albumid',
            field=models.ForeignKey(blank=True, db_column='albumid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='albums.Album'),
        ),
        migrations.AlterField(
            model_name='track',
            name='genreid',
            field=models.ForeignKey(blank=True, db_column='genreid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='genres.Genre'),
        ),
        migrations.AlterField(
            model_name='track',
            name='mediatypeid',
            field=models.ForeignKey(blank=True, db_column='mediatypeid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='mediaTypes.MediaType'),
        ),
    ]
