# Generated by Django 3.0.4 on 2020-03-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_auto_20200324_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
