# Generated by Django 3.0.4 on 2020-06-01 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0004_auto_20200601_0053'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
