# Generated by Django 3.0.4 on 2020-03-22 03:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('albumid', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=30)),
                ('artistid', models.ForeignKey(db_column='artistid', on_delete=django.db.models.deletion.DO_NOTHING, to='artists.Artist')),
            ],
            options={
                'db_table': 'album',
            },
        ),
    ]
