# Generated by Django 3.0.4 on 2020-03-24 06:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracks', '0002_auto_20200324_0620'),
        ('userTracks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertrack',
            name='trackid',
            field=models.ForeignKey(blank=True, db_column='trackid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracks.Track'),
        ),
        migrations.AlterField(
            model_name='usertrack',
            name='userid',
            field=models.ForeignKey(blank=True, db_column='userid', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
