# Generated by Django 3.0.4 on 2020-05-17 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userTracks', '0002_auto_20200324_0620'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertrack',
            name='relation',
            field=models.CharField(default='uploaded', max_length=50),
        ),
    ]
