# Generated by Django 3.0.4 on 2020-06-01 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userTracks', '0003_usertrack_relation'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertrack',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
