# Generated by Django 3.0.4 on 2020-06-01 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userTracks', '0004_usertrack_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertrack',
            name='url',
        ),
    ]
