# Generated by Django 3.0.4 on 2020-03-24 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('playlists', '0001_initial'),
        ('tracks', '0002_auto_20200324_0620'),
        ('playlistTracks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlisttrack',
            name='playlistid',
            field=models.ForeignKey(db_column='playlistid', on_delete=django.db.models.deletion.CASCADE, to='playlists.Playlist'),
        ),
        migrations.AlterField(
            model_name='playlisttrack',
            name='trackid',
            field=models.ForeignKey(db_column='trackid', on_delete=django.db.models.deletion.CASCADE, to='tracks.Track'),
        ),
    ]
