# Generated by Django 3.0.4 on 2020-06-01 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppingcarts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shoppingcart',
            old_name='userid',
            new_name='user',
        ),
    ]
