# Generated by Django 3.0.4 on 2020-03-22 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('invoiceLines', '0001_initial'),
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceline',
            name='trackid',
            field=models.ForeignKey(db_column='trackid', on_delete=django.db.models.deletion.DO_NOTHING, to='tracks.Track'),
        ),
    ]
