# Generated by Django 3.0.4 on 2020-03-24 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_auto_20200324_0620'),
        ('tracks', '0001_initial'),
        ('invoiceLines', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoiceline',
            name='invoiceid',
            field=models.ForeignKey(blank=True, db_column='invoiceid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.Invoice'),
        ),
        migrations.AlterField(
            model_name='invoiceline',
            name='trackid',
            field=models.ForeignKey(blank=True, db_column='trackid', null=True, on_delete=django.db.models.deletion.SET_NULL, to='tracks.Track'),
        ),
    ]
