# Generated by Django 3.0.4 on 2020-06-01 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceLines', '0002_auto_20200324_0620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoiceline',
            old_name='invoicelineid',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='invoiceline',
            old_name='invoiceid',
            new_name='invoice',
        ),
        migrations.RenameField(
            model_name='invoiceline',
            old_name='trackid',
            new_name='track',
        ),
    ]
