# Generated by Django 3.0.4 on 2020-03-23 01:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employeeid', models.IntegerField(primary_key=True, serialize=False)),
                ('lastname', models.CharField(max_length=20)),
                ('firstname', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=30)),
                ('birthdate', models.DateTimeField()),
                ('hiredate', models.DateTimeField()),
                ('address', models.CharField(max_length=70)),
                ('city', models.CharField(max_length=40)),
                ('state', models.CharField(max_length=40)),
                ('country', models.CharField(max_length=40)),
                ('postalcode', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=24)),
                ('fax', models.CharField(max_length=24)),
                ('email', models.CharField(max_length=60)),
                ('reportsto', models.ForeignKey(db_column='reportsto', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='employees.Employee')),
            ],
            options={
                'db_table': 'employee',
            },
        ),
    ]
