# Generated by Django 3.0.4 on 2020-03-09 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_streaming', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artist',
            options={},
        ),
    ]
